# Generated by Django 4.0.4 on 2022-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='2022-04-28'),
            preserve_default=False,
        ),
    ]
