# Generated by Django 4.0.4 on 2022-05-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_comment_paent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='paent',
            new_name='parent',
        ),
    ]
